steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend:latest'
      - '.'

  # Push the Docker images to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/$PROJECT_ID/backend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--min-instances=1'
      - '--max-instances=5'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=300s'
      - '--concurrency=80'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production,GCP_PROJECT_ID=saas-tf-production,GCP_ZONE_NAME=saas-tf-zone,GCP_DNS_DOMAIN=saas.tf,FRONTEND_URL=https://saas.tf,RATE_LIMIT_ENABLED=true,RATE_LIMIT_WINDOW_MS=900000,RATE_LIMIT_MAX_REQUESTS=100,LOG_LEVEL=info,JWT_EXPIRES_IN=30d'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,STRIPE_PRICE_ID_PACKAGE_5=STRIPE_PRICE_ID_PACKAGE_5:latest,STRIPE_PRICE_ID_PACKAGE_50=STRIPE_PRICE_ID_PACKAGE_50:latest,SENDGRID_API_KEY=SENDGRID_API_KEY:latest,SENDGRID_FROM_EMAIL=SENDGRID_FROM_EMAIL:latest,GCP_SERVICE_ACCOUNT_JSON=GCP_SERVICE_ACCOUNT_JSON:latest'
      - '--add-cloudsql-instances=saas-tf-production:us-central1:saas-tf-db'
      - '--service-account=cloud-run-backend@saas-tf-production.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'  # 20 minutes
